Bump minor version
Siderus/Orion pull request #171
Opened 2018-08-08 18:49 UTC by 0x6431346e

## What changed?
Insert here the changes.

2018-08-08 18:54 UTC, koalalorenzo commented
Changes:

- Add row selection to StorageList #150
- Updates Readme, Deb and Dependencies #157
- Upgrade IPFS to v0.4.16 #158 
- Upgrade ipfs binaries to v0.4.17 #167
- Fix the files tab on the property window #159
- Track app updates #160
- Add copy to clipboard to details window #161
- Upgrade dependencies #164
- Adds debian repo and triggers #166 ( get.siderus.io )
- Make import from hash an activity #165
- Setup tray icon after the app started, not before #170 ( Closed #156 )
- Persist activities to a file #169

2018-08-08 21:47 UTC, koalalorenzo commented
Jumping from 0.4.15 to 0.4.17 requires migration: 

```
Running /Users/koalalorenzo/Repositories/Siderus/Orion/go-ipfs/ipfs [ 'config', 'Addresses.API' ]
/Users/koalalorenzo/Repositories/Siderus/Orion/go-ipfs/ipfs config,Addresses.API: Error: ipfs repo needs migration
```

The app won't start and goes into timeout.

2018-08-09 07:25 UTC, 0x6431346e commented
Finished the repo migration feature, to test in dev:
- first delete the current repo (`rm -rf ~/.config/Electron/ipfs-repo`)
- run `IPFS_PATH=~/.config/Electron/ipfs-repo ipfs init` with an older binary (my globally installed ipfs is 0.4.14)
- running `IPFS_PATH=~/.config/Electron/ipfs-repo ipfs repo stat` shows  `Version:    fs-repo@6`
- `make run` will now start Orion and before starting the daemon it will run migrations:

```
Running /home/daniel/repos/siderus/orion/fs-repo-migrations/fs-repo-migrations -y { env: { IPFS_PATH: '/home/daniel/.config/Electron/ipfs-repo' } }
Finished /home/daniel/repos/siderus/orion/fs-repo-migrations/fs-repo-migrations -y with:  Found fs-repo version 6 at /home/daniel/.config/Electron/ipfs-repo
===> Running migration 6 to 7...
applying 6-to-7 repo migration
migrating IPNS record for key: self
updated version file
===> Migration 6 to 7 succeeded!
```

2018-08-09 08:16 UTC, koalalorenzo requested changes

2018-08-09 08:16 UTC, koalalorenzo commented on Makefile
> +prepare_binaries:
write like this:

```
prepare_binaries: prepare_ipfs_bin prepare_repo_migrations_bin
.PHONY: prepare_binaries
```

2018-08-09 08:16 UTC, koalalorenzo commented on app/index.js
> +          .then(ensureRepoMigrated)
Run this before the daemon configured.

2018-08-09 17:46 UTC, koalalorenzo approved these changes
It works! :D

2018-08-09 17:46 UTC, merged